"""manual upload and part count

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-11 15:17:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models_3d', sa.Column('part_count', sa.Integer(), nullable=True))
    op.alter_column('models_3d', 'telegram_file_id',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('models_3d', 'telegram_message_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('models_3d', 'telegram_message_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('models_3d', 'telegram_file_id',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('models_3d', 'part_count')
    # ### end Alembic commands ###
